//
// This header file manages the calculation and creation of fields.
//

#include "readOptProperties.h"      // Reads user-defined optimization properties
#include "readThermProperties.h"    // Reads thermal properties
#include "readTransProperties.h"    // Reads transport properties
#include "setDensityFields.h"       // Sets fields related to zones and pseudo density gamma
#include "setTransFields.h"         // Sets fields related to transport properties
#include "setThermFields.h"         // Sets fields related to thermal properties
#include "setSensFields.h"          // Sets fields related to adjoint sensitivity
