//
// This header file manages the calculation and creation of fields.
//

#include "readOptProperties.h"          // Read user-defined optimization properties
#include "setDensityFields.h"           // Sets fields related to zones and pseudo density gamma
#include "readTransProperties.H"        // Read and set fields related to transport properties
#include "readThermProperties.H"        // Read and set fields related to thermal properties
#include "readMechanicalProperties.H"   // Read and set fields related to mechanical properties
